package com.javaguru.student_igors_jurkovs.lesson_13.level_5_middle.validation_rules;

public enum RuleDescription {

    PRODUCT_NAME_CANT_BE_BLANK,
    PRODUCT_NAME_CANT_BE_LESS_THAN_3_SYMBOLS,
    PRODUCT_NAME_CANT_BE_MORE_THAN_100_SYMBOLS,
    PRODUCT_NAME_CAN_CONTAIN_ONLY_EN_CHARS_AND_NUMBERS,

    PRICE_CANT_BE_EMPTY,
    PRICE_CAN_CONTAIN_ONLY_NUMBERS,
    PRICE_CANT_BE_0,

    DESCRIPTION_CANT_BE_LONGER_THAN_2000_SYMBOLS,
    DESCRIPTION_CAN_CONTAIN_ONLY_EN_CHARS_AND_NUMBERS

}
